package db.clorabase.clorem;

public enum Reasons {
    REASONS_UNKNOWN,
    REASONS_DATABASE_CREATION_ERROR,
    REASONS_NODE_CREATION_ERROR,
    REASONS_DATABASE_CORRUPTED,
    REASONS_QUERY_ERROR,
    REASONS_INVALID_TYPE,
    REASONS_NOT_EXISTS
}
