package com.clorem.db;

public enum Reasons {
    REASONS_UNKNOWN,
    REASONS_DATABASE_CREATION_ERROR,
    REASONS_NODE_NOT_FOUND,
    REASONS_DATABASE_CORRUPTED,
    REASONS_NODE_EXPECTED,
    REASONS_INVALID_TYPE,
}
